# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      test:
        type: boolean
        description: True if yes, false otherwise
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "${{ inputs.test }}"
